Add couchdb manage function to update couchapps
dmwm/deployment pull request #1045
Opened 2021-04-16 19:37 UTC by goughes

Adds an "updatecouchapps" function to the couchdb manage script that pulls couchapps from the WMCore github repo.  Services like reqmgr2/reqmon used to run alongside couchdb on the VMs and would pull the couchapps in with their RPMS. Now they are running in k8s, so we need a way to update and deploy couchapps on the couchdb VMs.

More info here: https://github.com/dmwm/WMCore/issues/10216

This only deals with pulling and updating the couchapp versions on the couchdb VMs. Additional work is being done to determine a new method for pushing the couchapps.

FYI, @amaltaro

2021-04-19 18:26 UTC, goughes commented
Looks like there will need to be some further investigation for Reqmon on the minification of some of these js files. More info here:
https://github.com/dmwm/WMCore/wiki/WMStats#deployment
https://github.com/dmwm/WMCore/blob/master/bin/combineMinifyWMStats.py

2021-04-20 18:28 UTC, goughes commented
The combineMinifyStats.py script is not part of the RPM build process. It is run manually when making changes to certain WMStats js files. Added the remaining files for WMStats with the latest commit. File counts/lists are now the same for each couchapp between this deployment method and the RPM based one.

2021-04-27 14:02 UTC, amaltaro commented
@goughes Erik, thanks for providing these changes.

Now that I look at the directories you use to store the couchapps code
```
  local couchdb_dir=/data/srv/current/apps/couchdb
  local couchapps_dir=$couchdb_dir/data
```

I have the impression that it will only work until CouchDB gets restarted. If it gets restarted, then it will likely load the previous couchapps, as instructed from the `stagingarea` files, e.g.:
```
couchapp push /data/srv/current/apps/reqmgr2/data/couchapps/ReqMgr http://localhost:5984/reqmgr_workload_cache
```

I think there are a couple of ways to deal with this, like:
a) once we download the source code, we need to make a copy of them under the corresponding directories (/data/srv/current/apps/reqmgr2, /data/srv/current/apps/workqueue, etc). However, we will likely have permissions issues.
b) update the deployment script to actually set the stagingarea with the couchdb path, e.g.:
https://github.com/dmwm/deployment/blob/master/reqmgr2/deploy#L53-L66

For case b), we would have to update all the deployment scripts defining files under the couchdb stagingarea though, thus instead of:
```
echo "couchapp push $reqmgrapp/data/couchapps/ReqMgrAux" 
```
something like:
```
echo "couchapp push $couchdbapp/data/couchapps/ReqMgrAux" 
```

What do you think?

2021-04-29 14:43 UTC, goughes commented
I made changes that make the stagingarea on the couch VMs obsolete. We can remove those files manually and they won't come back since the services that used to write them (reqmgr2, reqmon, etc.) are now in the k8s cluster.

2021-05-04 20:49 UTC, goughes commented
With the latest commit, the couchapps location was moved to the `stagingarea` of couchdb. Couchapps are pulled from the WMCore version marked as "latest" if they do not already exist at this location. Tested this script with a new deployment of couchdb on my test VM and things worked fine. 

@amaltaro Can you take at my latest changes and let me know if you have questions/comments.

2021-05-07 05:06 UTC, amaltaro requested changes
Erik, this code is looking pretty good. However, I think we can make it more solid by swapping a few lines (I left a comment in the code). The couch views is something that worries me a bit as well, but if it was already like that, then I guess I shouldn't bother.

Last but not least, since the old files in the `stagingarea` will no longer be needed, can you please go through those services and remove those blocks from their `post` step, e.g.:
https://github.com/dmwm/deployment/blob/master/reqmon/deploy#L53-L63

I'd suggest to keep those cleanup in a 2nd commit if possible. Thanks!

2021-05-07 05:06 UTC, amaltaro commented on couchdb/manage
> +    # clean views
This "clean views" block is something that surprises me, and it looks like the logic is the same as it was before, thus: every time we push couchapps in (no matter where there were changes or not), we trigger this database view cleanup. Did I understand this logic correctly?

And the problem with that logic is, every time we redeploy CouchDB, it will cleanup (delete?) all the couch views, which will trigger a massive rebuild of the views, especially in databases with large and/or millions of documents.

Even if the logic did not change compared to the current version, this is something that we must verify in the upcoming testbed/production deployment.

2021-05-13 15:57 UTC, goughes commented on couchdb/manage
> +  rm -rf $couchapps_dir/couchapps &> /dev/null
I agree, this is fixed in my latest commit.

2021-05-13 16:00 UTC, goughes commented
@amaltaro I made the requested changes and added the `-p` and `-c` options for the new CMSCouchapp. Take a look when you have time.

Working on a second commit to clean up the old `post` steps for each service.

2021-05-17 17:06 UTC, amaltaro commented
Thanks Erik, these changes are looking good to me. Can you please confirm whether it's ready to be merged from your side? @goughes

2021-05-18 13:55 UTC, goughes commented
Looks good from my side. Go ahead and merge.

2021-05-19 16:50 UTC, merged

2021-05-21 09:26 UTC, amaltaro commented
@goughes you probably remember that one of my concerns was the continuous view cleanup performed every time we push in new couchapps. 

I decided to monitor a CouchDB redeployment in testbed, and didn't see any active tasks right after the service was started.
Looking at the code you provided and the CouchDB 1.6.1 documentation:
https://docs.couchdb.org/en/1.6.1/api/database/compact.html?highlight=_view_cleanup#db-view-cleanup

it's now clear to me that we should indeed not expect any problems with that, since it will only remove views that are no longer needed (instead of removing all of them, as I initially thought!). Cheers!