DQM^2 offsite access
dmwm/deployment pull request #1050
Opened 2021-04-30 12:51 UTC by pmandrik

Add DQM^2 site and redirection rules to the list.
WIP:

- the machine to run the server is  `srv-c2f11-29-02`, same as for online|online-playback|online-test|online-new|online-playback-new|online-test-new sites => because of this, from my understanding, need to specify a different specific port to listen at [0] => need to figure out available ports and firewall settings

[0] https://github.com/pmandrik/deployment/blob/0d5da1dd565bdf714bcfeb0985e94ec0e3ef0149/frontend/app_dqm_ssl.conf#L11

2021-04-30 13:04 UTC, muhammadimranfarooqi requested changes
I think you dont need to add new line for this. You can include `dqm-square` in line 2 in `app_dqm_nossl.conf`. No need to specify the port for machines at P5.

2021-05-06 12:26 UTC, pmandrik commented
> I think you dont need to add new line for this. You can include `dqm-square` in line 2 in `app_dqm_nossl.conf`. No need to specify the port for machines at P5.

Ok, thanks, fixed!

2021-05-12 08:12 UTC, muhammadimranfarooqi commented
@pmandrik 

Please add entries in `backends-k8s-prod.txt`  and `backends-k8s-preprod.txt`  as well similar to `backends-prod.txt`.

2021-05-12 14:09 UTC, pmandrik commented
@muhammadimranfarooqi 
Done!

2021-05-15 09:37 UTC, merged

2021-05-16 17:06 UTC, muhammadimranfarooqi commented
@pmandrik 

I have deployed it in https://cmsweb-prod.cern.ch/ . It seems service is currently unavailable. Could you please test.

2021-05-17 11:58 UTC, pmandrik commented
@muhammadimranfarooqi 
Hi, the server is accessible from https://cmsweb-prod.cern.ch/ offsite. Thanks!