Add service configs for MSUnmerged VM based deployment.
dmwm/deployment pull request #1059
Opened 2021-06-14 20:01 UTC by todor-ivanov

These are the initial configuration for VM based setup for the MSUnmerged micro service.

2021-06-14 20:01 UTC, todor-ivanov commented
FYI: @amaltaro

2021-06-15 07:53 UTC, amaltaro requested changes
Thanks for providing these deployment changes, Todor. I have a few comments/suggestions along the code for your consideration.

And just a comment before I forget, which could be added here or in a later stage. I think we will need to have the ability to ban:
* a given RSE
* a given LFN (e.g., /store/unmerged/repack, etc)

even if we do not use it now, I'm pretty sure such flexibility will be needed in the future. So having a placeholder in the configuration would be useful.

2021-06-15 07:53 UTC, amaltaro commented on exporters/manage
> +    process_monitor.sh /data/srv/state/reqmgr2ms/ms-unmerged.pid ms_unmerged ":18242" 15 \
@muhammadimranfarooqi Imran, I see some process_status defined for vocms0742. Should we define one for ms_unmerged as well?

2021-06-15 07:53 UTC, amaltaro commented on reqmgr2ms/config-unmerged.py
> +    RUCIO_AUTH_URL="https://cms-rucio-auth.cern.ch"
Todor, I would suggest to start the service configuration with the bare minimum. It's always easier to spot and add things, than to remove unneeded ones ;)
These RUCIO related variables and the archival delay hours is probably better to be gone.

2021-06-15 07:53 UTC, amaltaro commented on reqmgr2ms/config-unmerged.py
> +if DBS_INS == "private_vm":
DBS is also not needed.

2021-06-15 07:53 UTC, amaltaro commented on reqmgr2ms/monitoring-unmerged.ini
> +PING_URL="http://localhost:8244/ms-unmerged/data/status"
Isn't the port supposed to be 8242?

2021-06-15 07:55 UTC, amaltaro commented
@todor-ivanov can you please link all the services_config merge requests to this deployment PR as well? It's easier to find and track changes this way.
Last but not least, once you apply changes to this PR, you need to replicate them to the services_config merge requests as well.

2021-06-15 09:08 UTC, muhammadimranfarooqi commented on exporters/manage
> +    process_monitor.sh /data/srv/state/reqmgr2ms/ms-unmerged.pid ms_unmerged ":18242" 15 \
@amaltaro @todor-ivanov 
I think there is no need to define process_status for vocms0742, as the service will be deployed on k8s not in VM. Right?

2021-06-15 09:10 UTC, muhammadimranfarooqi commented on reqmgr2ms/monitoring-unmerged.ini
> +PING_URL="http://localhost:8244/ms-unmerged/data/status"
@todor-ivanov 

Yes, port should be `8242`

2021-06-15 09:29 UTC, todor-ivanov commented on reqmgr2ms/config-unmerged.py
> +    RUCIO_AUTH_URL="https://cms-rucio-auth.cern.ch"
We need a Rucio account for sure. Just need to decide which one to use so we can simplify it here. While the for the archival delay parameter I just forgot to remove. Doing it now .

2021-06-15 09:30 UTC, todor-ivanov commented on reqmgr2ms/monitoring-unmerged.ini
> +PING_URL="http://localhost:8244/ms-unmerged/data/status"
oops, I missed one spot.

2021-06-15 09:31 UTC, todor-ivanov commented on exporters/manage
> +    process_monitor.sh /data/srv/state/reqmgr2ms/ms-unmerged.pid ms_unmerged ":18242" 15 \
I still need to full VM configuration for my personal development environment.

2021-06-15 09:42 UTC, todor-ivanov commented on reqmgr2ms/config-unmerged.py
> +if DBS_INS == "private_vm":
removing it now

2021-06-15 10:12 UTC, todor-ivanov commented on reqmgr2ms/config-unmerged.py
> +    RUCIO_AUTH_URL="https://cms-rucio-auth.cern.ch"
Keeping just `wmcore_transferor` for the time being.

2021-06-15 20:03 UTC, amaltaro commented on exporters/manage
> +    process_monitor.sh /data/srv/state/reqmgr2ms/ms-unmerged.pid ms_unmerged ":18242" 15 \
That's correct, Imran. The process_status is attached to vocms0742, so I think we can indeed just skip that.

2021-06-15 20:08 UTC, amaltaro requested changes
Todor, as we discussed over slack this afternoon, we still need to have rucio-related information in the configuration because the LFN to PFN translation will be done via Rucio.

The current configuration needs to be reworked, I have made a comment or two along the code.

2021-06-15 20:08 UTC, amaltaro commented on reqmgr2ms/config-unmerged.py
> +data.rucioMstrAccount = RUCIO_MSTR_ACCT
I suggest to keep only the `rucioAccount`, and remove the WmaAccount and MstrAccount attributes (those variables getting assigned to it are not defined anyways).

Todor, my previous comment has probably mislead you, sorry. We still need the rucio/auth urls for this service (but they are not defined). Can you please fix this as well?

2021-06-15 21:08 UTC, todor-ivanov commented on reqmgr2ms/config-unmerged.py
> +data.rucioMstrAccount = RUCIO_MSTR_ACCT
@amaltaro  WmaAccount and MstrAccount are already removed. This one is just a leftover(which BTW will cause the deploayment to fail because RUCIO_MSTR_ACCT does not exist any more) , I have missed that spot. Thanks for catching it. I am fixing that one too.

2021-06-15 22:10 UTC, amaltaro commented on reqmgr2ms/config-unmerged.py
> +RUCIO_ACCT = "wmcore_transferor"
You still need to bring back some of the changes you had in your first commit, these:
```
if BASE_URL == "https://cmsweb.cern.ch":
            RUCIO_AUTH_URL="https://cms-rucio-auth.cern.ch"
            RUCIO_URL="http://cms-rucio.cern.ch"
else:
            RUCIO_AUTH_URL="https://cmsrucio-auth-int.cern.ch"
            RUCIO_URL="http://cmsrucio-int.cern.ch"
```

2021-06-15 22:49 UTC, todor-ivanov commented on reqmgr2ms/config-unmerged.py
> +RUCIO_ACCT = "wmcore_transferor"
Thanks @amaltaro
Fixxed!

2021-06-24 23:48 UTC, todor-ivanov commented
Hi @muhammadimranfarooqi @vkuznet I will need  this one merged  too

2021-06-24 23:55 UTC, todor-ivanov commented
FYI @amaltaro

2021-06-25 04:04 UTC, amaltaro approved these changes
Changes look good to me, thanks, Todor.

2021-06-25 04:04 UTC, amaltaro commented on reqmgr2ms/config-unmerged.py
> +DBS_INS = "@@DBS_INS@@"
To be removed in the future, we seem not to use it in the configuration.

2021-06-25 08:15 UTC, merged

2021-06-26 08:22 UTC, amaltaro commented on reqmgr2ms/config-unmerged.py
> +data.reseExpr = RSEEXPR
@todor-ivanov Todor, please fix this typo (also in the other repository and branches).