Initial manage/config changes for CouchDB 3.1.2
dmwm/deployment pull request #1088
Opened 2021-08-26 15:03 UTC by amaltaro

Fixes https://github.com/dmwm/WMCore/issues/10829

Let me try to document all the changes and why they have been made:
* `couchdb/default.ini`, `wmagentpy3/default.ini` and `tier0/default.ini` configuration file is required to start up CouchDB. This is a blind copy of what is provided by CouchDB itself.
* `local.ini` configuration file contains our specific CouchDB configuration, overriding whatever is in the `default.ini`
  * `chttpd/authentication_handlers` define the Proxy Authentication mechanism
  * `couchdb/single_node` defined to true to get the admin users automatically created during deployment, in addition to some system-like databases
* `manage` script required a few changes, like:
  * database/management calls need to be made with user/pass, even if it's all localhost!
  * `couchdb -p`, `couchdb -a`, `couchdb -o`, `couchdb -e` and `couchdb -b` no longer exist, removed!
  * `couchdb -A` has been replaced by `couchdb -couch_ini`
  * adapted the `start` and `stop` code
  * CouchDB `status` now uses the `_up` unathenticated endpoint
  * pushing couchapps follow exactly the same logic, only difference is that it uses for loop now
* `couchdb/monitoring.ini` needs to use user/pass (set up during couchdb deployment)
*  `wmagentpy3/deploy` position CouchDB config files under the `couchdb` configuration directory
* `wmagentpy3/local.ini` defines 2 accounts, the admin one and unittest users. The unittest user will be disabled when CouchDB gets deployed in production. These accounts are automatically created during start up.
* `wmagentpy3/manage` is a mess and it makes our CI jenkins hard to deal with. 
* for central CouchDB deployment and `manage` script operations, read credentials from `couch_creds` file.
* define `max_replication_retry_count` to infinity for WMAgent/Tier0 backend
* define replication `connection_timeout` to 300 secs (I've seen timeouts in testbed replications!)

In addition to that, it also includes:
* changes to `reqmgr2ms/manage` such that MSOutput and MSUnmerged do not get started in our VMs (MongoDB setup is broken).

TODO: Imran, we need to define a file for the Couch credentials under /data/auth/couchdb. We can discuss this over Mattermost.

2022-05-24 15:08 UTC, amaltaro commented on couchdb/manage
> +    kill -9 $couch_pid
For my own reference, this logic to kill the couchdb process in my private VM does not work. It fails and it exits the script, thus never starting CouchDB. Here is the relevant terminal output:
```
+ sudo -H -u $u bashs -lc '/data/srv/current/config/couchdb/manage stop '\''I did read documentation'\'''
Stopping CouchDB service...
  killing CouchDB process... 
/data/srv/current/config/couchdb/manage: line 229: kill: (11496) - Operation not permitted
  killing CouchDB process... 
/data/cfg/admin/InstallDev: line 89: 11496 Killed                  sudo -H -u $u bashs -lc "$cmd"
```

2022-05-31 21:52 UTC, amaltaro commented on wmagentpy3/local.ini
> +uuid = 652fb71bc6c32121e0752325a4973eb3
TODO: check if it's really necessary.

2022-05-31 22:02 UTC, amaltaro commented on wmagentpy3/manage
> +        &> $INSTALL_COUCH/logs/couch_nohup.log &
TODO: it's likely a good idea to rename this `couch_nohup.log` log by the usual `couch.log`

2022-06-01 13:53 UTC, vkuznet requested changes
Alan, I made few suggestions:
- there is a pattern of using `http://$USERPASS@localhost:5984`, therefore it is better to define it once and use across the code. For instance, if it was already there then you don't need to change so many places.
- you should replace all hard-coded couch credentials in all files since you'll push these files into github and we should avoid leakage of credentials (even for our backends)
- usage of perl is not required but leads to increase size of RPMs, therefore I suggest to replace it with sed.

2022-06-01 13:53 UTC, vkuznet commented on couchdb/manage
> +USERPASS=admin:myadminpasswd
You should not define your actual values here since manage script is pushed to public github repo where everyone can find it. Instead you need to check that some env variable exists, e.g.
```
if [ -z "$COUCH_CREDENTIALS" ]; then
   echo "please define $COUCH_CREDENTIALS"
   exit 1
fi
```
This block will check existance of `COUCH_CREDENTIALS` (the name does not matter) which will be setup either by deployment script (post action) or in k8s via secrets. This will allow to keep credentials out of this manage script

2022-06-01 13:53 UTC, vkuznet commented on couchdb/manage
> +  local TASKS=$(curl -s $USERPASS@localhost:5984/_active_tasks)
if you fix this then use URI schema, i.e.
`curl -s http://$USERPASS@localhost:5984/_active_tasks`

2022-06-01 13:53 UTC, vkuznet commented on couchdb/manage
> +  curl -s -H "Content-Type: application/json" -X POST http://${USERPASS}@localhost:5984/$database/_view_cleanup | \
if you adapt `couchCurl` definition, then this call will be replaced as
```
curl -s -H "Content-Type: application/json" -X POST $couchHost/$database/_view_cleanup | \
```

2022-06-01 13:53 UTC, vkuznet commented on couchdb/monitoring.ini
> +PING_URL="http://admin:myadminpasswd@localhost:5984/workqueue/_design/WorkQueue/_rewrite/"
This is bad from security point of view as this file will be pushed to github. Instead, as I proposed for manage script you should rely on env variable and read from it couch credentials.

2022-06-01 13:53 UTC, vkuznet commented on frontend/cmsauth.pm
> +    $hdrs{"x-auth-couchdb-username"} = "admin";
This is security flaw again, I suggest to read values from env variables, instead of hard-code them

2022-06-01 14:10 UTC, vkuznet commented
Regarding security measurements, according to Couch docs we can define group members via simple PUT HTTP request:
```
curl http://localhost:5984/OUR_DB/_security \
-X PUT -H 'content-type: application/json' \
-H 'accept: application/json' \
-d '{"admins":{"names":["dmwm"],"roles":["admins"]},"members":{"names": ["user1","user2"],"roles": ["developers"]}}'
```
Here, we create new users for `OUR_DB` database. The `dmwm` user has role `admins`, while `user1,user2` have role `developers`. I suggest to make separate shell script with this curl template and add it to repository. Then, during deployment phase we can use a script with provided parameters to add new members, e.g.
```
#!/usr/bin/env bash
db=$1
name=$2
role=$3
# perform update in couchdb to assign new member to a given database
curl http://localhost:5984/$db/_security \
   -X PUT -H 'content-type: application/json' \
   -H 'accept: application/json' \
   -d '{"admins":{"names":["$name"],"roles":["$role"]}}`
```

2022-06-01 22:57 UTC, amaltaro commented on workqueue/monitoring.ini
> +PING_URL="http://admin:myadminpasswd@localhost:5984/workqueue/_design/WorkQueue/_rewrite/_show/status/task_activity"
This isn't a bash file, I guess loading credentials from a file name won't work. But I will give it a try.

2022-06-02 11:43 UTC, amaltaro commented on wmagentpy3/manage
> +    perl -p -i -e "s{bind_address = 127.0.0.1}{bind_address = $COUCH_HOST}g" $CONFIG_COUCH/local.ini
About replacement of perl by sed, I'd rather leave it for the next step, once everything is functional, tested and deployed. I am being as conservative as I can with these changes.

2022-06-02 14:59 UTC, vkuznet commented on frontend/cmsauth.pm
> +    $hdrs{"x-auth-couchdb-username"} = "admin";
this a perl script, therefore it can reads env variables (even though I don't know how it is done in perl). Therefore, I suggest to replace `"admin"` with perl function which will read `COUCH_ADMIN` environment variable, if it is not set it should exit with error.

2022-06-02 19:51 UTC, amaltaro commented on workqueue/monitoring.ini
> +PING_URL="http://_admin:_admin@localhost:5984/workqueue/_design/WorkQueue/_rewrite/_show/status/task_activity"
TODO: this should be removed before merging. Actually, this ping test is no longer meaningful, since workqueue runs in k8s where couchdb is not available in localhost.

2022-06-02 19:53 UTC, amaltaro commented on frontend/cmsauth.pm
> +    $hdrs{"x-auth-couchdb-username"} = "_admin";
TODO: It looks like Valentin's comment is gone with a change I made in this line. Bottom line is, we need to investigate how to load this value from a file/environment variable.

2022-06-16 19:06 UTC, amaltaro commented
@muhammadimranfarooqi Imran, as discussed today, I separated the frontend changes (and a TODO monitoring.ini) in this PR: https://github.com/dmwm/deployment/pull/1151

Could you please review and merge this one?

2022-06-21 20:23 UTC, amaltaro commented on couchdb/monitoring.ini
> +PING_URL="http://@@@USER:@@@PASS@localhost:5984/workqueue/_design/WorkQueue/_rewrite/"
rollback

2022-06-23 20:45 UTC, amaltaro commented
All right! I think I resolved all the questions and concerns in this PR, other than the migration from perl to sed that goes beyond the scope of these changes.

@muhammadimranfarooqi I have all these things tested in my VM and from my side they are ready to go. Note that it does not require any changes to the frontends!

Regarding testbed deployment, please do not proceed with it because we will have to run the first upgrade together. Actions need to be taken to migrate the databases to a CouchDB 3.x format. It would be great to have it merged sooner though.

2022-06-24 13:30 UTC, merged