Add couchdb exporter secret file parameter
dmwm/deployment pull request #1156
Opened 2022-06-30 14:46 UTC by mrceyhun

@amaltaro @vkuznet @muhammadimranfarooqi 

According to the exporter [documentation](https://github.com/gesellix/couchdb-prometheus-exporter#run-the-binary), providing couchdb secrets to the exporter should be like this. I though secret file is more secure than environment variables, but we can change according to your calls.

Config file should be like:
```
$> cat couchdb_config.ini
couchdb.username=admin
couchdb.password=somepassword
```

2022-06-30 14:57 UTC, vkuznet requested changes

2022-06-30 14:57 UTC, vkuznet commented on exporters/manage
> +COUCHDB_EXP_SEC_FILE=couchdb_config.ini
I suggest to adjust it to something like
```
COUCH_SECFILE="${couchdb_config.ini:-/etc/secrets/couchdb_config.ini}" 
```
In other words, assign variable with default pointing to k8s secret. Moreover, you should ensure that couchdb_conifg.ini permission should be 0400.

2022-06-30 15:29 UTC, mrceyhun commented on exporters/manage
> +COUCHDB_EXP_SEC_FILE=couchdb_config.ini
Applied the suggestion and put a check function for the secret file

2022-06-30 15:38 UTC, vkuznet approved these changes

2022-06-30 15:54 UTC, mrceyhun commented on exporters/manage
> +COUCH_SECFILE="${couchdb_config.ini:-/etc/secrets/couchdb_config.ini}"
@amaltaro you're right, first one should be variable. After the exact path of the secret I'll fix the PR.

Muhammad provided the secrets to me and it worked (I tested with different port 1684):
```
./couchdb_exporter -couchdb.uri=http://localhost:5984 -logtostderr=true --config=/tmp/ceyhun/couchdb_config.ini -databases=workqueue,workqueue_inbox,wmstats,workloadsummary,wmstats_logdb -databases.views=false -telemetry.address=:16984

cuzunogl@vocms0731 ~ $ curl http://localhost:16984/metrics
# HELP couchdb_database_compact_running database compaction running
# TYPE couchdb_database_compact_running gauge
couchdb_database_compact_running{db_name="wmstats"} 0
couchdb_database_compact_running{db_name="workqueue_inbox"} 0
# HELP couchdb_database_data_size data size
# TYPE couchdb_database_data_size gauge
couchdb_database_data_size{db_name="wmstats"} 8.744949e+06
couchdb_database_data_size{db_name="wmstats_logdb"} 216439
```

2022-06-30 19:35 UTC, amaltaro commented
Given that I wanted to start looking at the metrics of this new couchdb version ASAP, I updated the manage script in both testbed VMs, with something like:
```
+CFGDIR=$(cd $(dirname $0) && pwd)
+COUCH_CONFIG=$CFGDIR/couchdb_config.ini
plus couchdb_exporter ... --config=$COUCH_CONFIG
```
and restarted exporters (with file in the correct location and correct format). Now we have data in the CouchDB dashboard again.

Real fix is still coming out of this PR though. Thanks

2022-06-30 20:08 UTC, mrceyhun commented
Thanks @amaltaro . Should I set the secret path as you defined in the comment?

2022-07-01 09:07 UTC, mrceyhun commented
Modified accordingly

2022-07-01 14:33 UTC, merged