Introducing the msRuleCleaner configuration.
dmwm/deployment pull request #967
Opened 2020-10-21 15:53 UTC by todor-ivanov

This is the initial PR for creating the MSRuleCleaner configuration.

2020-10-23 05:45 UTC, amaltaro requested changes
Todor, I've pointed a few configuration parameters that are irrelevant for this microservice. Can you please remove those?

In addition to that, prometheus monitoring needs to be set with Imran/Valentin.

2020-10-23 05:45 UTC, amaltaro commented on exporters/manage
> +    process_monitor.sh /data/srv/state/reqmgr2ms/ms-rulecleaner.pid ms_rulecleaner ":18244" 15 \
@todor-ivanov this port will have to be opened on the backend running MSRuleCleaner. And I guess Valentin will have to do something else on the Prometheus side. Please discuss those with Imran and Valentin as well.

2020-10-23 05:45 UTC, amaltaro commented on reqmgr2ms/config-ruleCleaner.py
> +RULE_LIFETIME = 30 * 24 * 60 * 60  # 30 days
RULE_LIFETIME, SEND_NOTIFICATION and ENABLE_DATA_PLACEMENT are not needed in this service.

2020-10-23 05:45 UTC, amaltaro commented on reqmgr2ms/config-ruleCleaner.py
> +data.sendNotification = SEND_NOTIFICATION
not needed

2020-10-23 05:45 UTC, amaltaro commented on reqmgr2ms/config-ruleCleaner.py
> +data.interval = 60 * 60 * 1  # run it every hour
I'd set the interval to every 8h

2020-10-23 05:45 UTC, amaltaro commented on reqmgr2ms/config-ruleCleaner.py
> +data.defaultGroup = "DataOps"
not needed

2020-10-23 05:45 UTC, amaltaro commented on reqmgr2ms/config-ruleCleaner.py
> +data.excludeDataTier = []
not needed

2020-10-23 11:28 UTC, todor-ivanov commented on exporters/manage
> +    process_monitor.sh /data/srv/state/reqmgr2ms/ms-rulecleaner.pid ms_rulecleaner ":18244" 15 \
done

2020-10-23 11:34 UTC, todor-ivanov commented on reqmgr2ms/config-ruleCleaner.py
> +RULE_LIFETIME = 30 * 24 * 60 * 60  # 30 days
done

2020-10-23 11:35 UTC, todor-ivanov commented on reqmgr2ms/config-ruleCleaner.py
> +data.sendNotification = SEND_NOTIFICATION
Done

2020-10-23 11:36 UTC, todor-ivanov commented on reqmgr2ms/config-ruleCleaner.py
> +data.interval = 60 * 60 * 1  # run it every hour
Done

2020-10-23 11:37 UTC, todor-ivanov commented on reqmgr2ms/config-ruleCleaner.py
> +data.excludeDataTier = []
Done

2020-10-23 11:37 UTC, todor-ivanov commented on reqmgr2ms/config-ruleCleaner.py
> +data.defaultGroup = "DataOps"
Done

2020-10-23 12:31 UTC, amaltaro commented on reqmgr2ms/config-ruleCleaner.py
> +data.interval = 60 * 60 * 8  # run it every hour
bad comment, but I didn't say anything :)

2020-10-23 12:31 UTC, amaltaro commented on reqmgr2ms/config-ruleCleaner.py
> +# Allows or not some alert notifications to be sent to the production-admin egroup
another unneeded comment

2020-10-23 12:35 UTC, todor-ivanov commented on reqmgr2ms/config-ruleCleaner.py
> +data.interval = 60 * 60 * 8  # run it every hour
good you spotted that 
Done

2020-10-23 12:36 UTC, todor-ivanov commented on reqmgr2ms/config-ruleCleaner.py
> +# Allows or not some alert notifications to be sent to the production-admin egroup
Thanks for spotting this leftover too 
Done

2020-10-23 12:36 UTC, amaltaro approved these changes
Thanks Todor, it's looking good now!

2020-10-23 13:35 UTC, vkuznet commented
@todor-ivanov , the changes look fine to me, and, yes we will need to open port 18244 on a node to allow prometheus to scrape the metrics. Once it is done, please open corresponding [CMSMONIT](https://its.cern.ch/jira/projects/CMSMONIT) Jira ticket and provide name of the node and port to use.  In case of k8s you'll need to create a new k8s yaml file for this service and then we'll plug it in. For that see example how it is done for other reqmgr microservices, e.g. [ms-monitoring](https://github.com/dmwm/CMSKubernetes/blob/master/kubernetes/cmsweb/services/reqmgr2ms-monitor.yaml) and make new PR against CMSKubernetes. The new k8s yaml file should include your service name, ports, etc.

2020-10-23 14:19 UTC, muhammadimranfarooqi commented on exporters/manage
> +    process_monitor.sh /data/srv/state/reqmgr2ms/ms-rulecleaner.pid ms_rulecleaner ":18244" 15 \
@todor-ivanov @amaltaro 
I have opened 18244 port on backends.

2020-10-23 14:34 UTC, todor-ivanov commented on exporters/manage
> +    process_monitor.sh /data/srv/state/reqmgr2ms/ms-rulecleaner.pid ms_rulecleaner ":18244" 15 \
Thank you @muhammadimranfarooqi

2020-10-26 08:30 UTC, amaltaro commented
@todor-ivanov two other actions are required from your side:
1. create the CMSKubernetes yaml file, as pointed out by Valentin above (against this repo: https://github.com/dmwm/CMSKubernetes)
2. create the `preprod` and `prod` respective microservice configuration (against gitlab repo in: https://gitlab.cern.ch/cmsweb-k8s/services_config/-/tree/preprod)

Please link those to this PR once you get that done.
Imran, from my side, we can proceed with the next testbed deployment before Todor implement those.

2020-10-26 08:54 UTC, merged